# Generated by Django 4.1.3 on 2022-11-28 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URLEntry',
            fields=[
                ('unique_id', models.SlugField(blank=True, max_length=10, primary_key=True, serialize=False)),
                ('original_url', models.URLField()),
                ('count', models.IntegerField(default=0)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
    ]
